### ISSUE TITLE
Readme in Bahasa

### ISSUE THREAD

**Issue by axmad386** [kodepintar/laravel-rajaongkir#3]
# README in Bahasa Indonesia
RajaOngkir is mainly use in Indonesia. So we need README in bahasa. PR is welcome

**Comment by kinkusuma** [comment]
Hai, boleh di assign?

**Comment by axmad386** [comment]
Hi @kinkusuma, maaf afk. Sebaiknya dibuat baru saja README-ID.md, isinya sementara disamain dulu saja. Nanti gampang di README utama dikasih link ke yang versi indonesia. Karena nanti kedepannya akan ada perubahan di README utama. Ada penambahan petunjuk instalasi bagi kontributor

**Comment by axmad386** [comment]
impemented in #4. I will close this issue
